library(oce)
try(source("~/src/oce/R/ctd.R"))
data(ctd)
ctd <- ctdAddColumn(ctd, ctd[["salinity"]]+10, "salinityPlus10", "S + 10")
if (!interactive()) png("595.png")
par(mfrow=c(2,1))
plot(ctd, which="salinity")
plot(ctd, which="salinityPlus10")
if (!interactive()) dev.off()
