library(oce)
cm1 <- colormap(name='test1.cpt')
cm2 <- colormap(name='test2.cpt')
cm3 <- colormap(name='test3.cpt')
cm4 <- colormap(name='test4.cpt')
print(cm1$missingColor)
print(cm2$missingColor)
print(cm3$missingColor)
print(cm4$missingColor)

