rm(list=ls())
if (!interactive()) png("516A.png", width=700, height=350)
library(oce)
try({
    source("~/src/oce/R/imagep.R")
})
library(oce)
data(adp)
par(mfrow=c(2,1))
zlim <- c(-0.2, 0.5)
imagep(adp[['v']][,,1], zlim=zlim, zclip=TRUE, missingColor='gray')
mtext(paste('EXPECT: gray below -0.2 and above 0.5'), col=6, font=2)
imagep(adp[['v']][,,1], zlim=zlim, zclip=FALSE, missingColor='gray')
mtext(paste('EXPECT: blue below -2 and red above 0.5'), col=6, font=2)
if (!interactive()) dev.off()

