library(oce)
#source("~/src/oce/R/imagep.R")
par(mfrow=c(1,2))
if (!interactive()) pdf("415AA.pdf")
drawPalette(c(0,1), zlab='415AA-1')
plot(1,1)
drawPalette(c(0,1), zlab='415AA-2')
plot(1,1)
if (!interactive()) dev.off()
