tmp <- tempfile(fileext=".rsk")
R.utils::decompressFile("sample.rsk.gz", destname=tmp, ext="gz", FUN=gzfile, remove=FALSE)
library(oce)
rsk <- read.rsk(tmp)
ctd <- as.ctd(rsk)
if (!interactive()) png("694_1_A.png")
plot(rsk)
if (!interactive()) dev.off()
if (!interactive()) png("694_1_B.png")
plot(ctd)
if (!interactive()) dev.off()
