library(oce)
## options("oce:test_sf"=1)
data(coastlineWorld)
if (!interactive()) png("1629_map.png")
par(mar=rep(0.5, 4))
mapPlot(coastlineWorld, projection="+proj=moll", debug=3)
if (!interactive()) dev.off()
