library(oce)
if (!interactive())
    png("issue387.png", unit="in", res=100, width=5, height=5, type="cairo")
par(mfrow=c(2,1), mar=rep(1, 4))
data(coastlineWorld)
data(topoWorld)
mapPlot(coastlineWorld)
mapImage(topoWorld, col=oceColorsGebco, zlim=c(-8000, 0))
mapPlot(coastlineWorld)
mapImage(topoWorld, col=rev(oceColorsGebco(100)), zlim=c(-8000, 0))
if (!interactive())
    dev.off()
