library(marmap)
library(oce)
try(source("~/src/oce/R/map.R"))
try(source("~/src/oce/R/topo.R"))
#a <- getNOAA.bathy(-90, 0, 00, 60, resolution=60)
a <- getNOAA.bathy(-120, 0, 0, 80, resolution=2*60)
t <- as.topo(a)
if (!interactive()) png("611B.png")
par(mfrow=c(2, 1))
plot(t, xlim=c(-120, 0), location="left")
mapPlot(t, proj="+proj=lcc +lon_0=-60 +lat_0=20 +lat_1=20", location="left")
if (!interactive()) dev.off()

