library(oce)
try(source("~/src/oce/R/ctd.R"))
data(ctd)
scanRange <- range(ctd[['scan']])
prange <- range(ctd[['pressure']])
newScanRange <- c(scanRange[1] + 20, scanRange[2] - 20)
if (!interactive()) png("670b.png")
par(mfrow=c(2,1))
plotScan(ctd, xlim=scanRange, ylim=prange)
abline(v=newScanRange, col='blue')
mtext('Original ctd object', adj=0)
mtext('(a) ', adj=1)
ctd_trimmed <- ctdTrim(ctd, "scan", parameters=newScanRange)
plotScan(ctd_trimmed, xlim=scanRange, ylim=prange)
abline(v=newScanRange, col='red')
mtext('EXPECT: trimmed to red lines, i.e. blue lines in (a)', col='magenta', font=2, adj=0)
mtext('(b) ', adj=1)
if (!interactive()) dev.off()
