library(oce)
if (!interactive()) png("1796a.png")
cm <- colormap(name="gmt_relief", debug=3)
par(mar=c(2,2,2,2))
drawPalette(colormap=cm, pos=3, debug=3)
plot(0:1,0:1,xlab="",ylab="",axes=FALSE,type="n")
text(0,0.5,"Case C: name=\"gmt_relief\"", pos=4)
if (!interactive()) dev.off()
