library(oce)
if (!interactive())
    png("2010a_%02d.png")
data(section)
s <- subset(section, longitude < -68)
blink <- rep(c(FALSE, TRUE), length.out=length(s[["longitude", "byStation"]]))
col <- ifelse(blink, 2, 4)
plot(s, which="map", col="white")
mtext("Expect: no trace or dots")
plot(s, which="map")
mtext("Expect: trace and +")
plot(s, which="map", pch=1)
mtext("Expect: trace and o")
plot(s, which="map", pch=1, cex=3)
mtext("Expect: trace and large O")
plot(s, which="map", pch=20)
mtext("Expect: trace and black bullets")
plot(s, which="map", col=2, pch=20)
mtext("Expect: trace and red bullets")
plot(s, which="map", col=col, pch=20)
mtext("Expect: trace and red/blue bullets")

P <- function(...) {
    projection <- "+proj=aea +lat_1=35 +lat_2=39 +lon_0=-70"
    plot(s, projection=projection, which="map", ...)
}
xlim <- c(-85, -65)
P(col="white")
mtext("Expect: map, water only")
P(col="white", map.xlim=xlim)
mtext("Expect: map with land+water")
P(map.xlim=xlim)
mtext("Expect: trace and +")
P(map.xlim=xlim, pch=1)
mtext("Expect: trace and o")
P(map.xlim=xlim, pch=1, cex=3)
mtext("Expect: trace and large O")
P(map.xlim=xlim, pch=20)
mtext("Expect: trace and black bullets")
P(map.xlim=xlim, col=2, pch=20)
mtext("Expect: trace and red dots")
P(map.xlim=xlim, col=col, pch=20)
mtext("Expect: trace and red/blue dots")
if (!interactive())
    dev.off()

