## Try reading ODF "adcp" manually. (NOTE: I think it's just one depth.)
library(oce)
file <- "MADCPS_hud2013021_1842_3380-69_3600.ODF"
d <- read.odf(file)
if (!interactive()) png("649b.png")
par(mfrow=c(3,1))
oce.plot.ts(d[["time"]], d[["u"]])
oce.plot.ts(d[["time"]], d[["v"]])
oce.plot.ts(d[["time"]], d[["w"]])
if (!interactive()) dev.off()
