if (!interactive()) png("432.png", width=7, height=7, unit="in", res=150, pointsize=12)
library(oce)
ctd <- read.ctd("~/Dropbox/CTD_JC066_7_003_loopedit.cnv")
ctdtrim <- ctdTrim(ctd, "range",parameters=list(item="pressure", from=12))
ctdtrim <- ctdTrim(ctdtrim, method='index', parameters=1:which.max(pressure(ctdtrim)))
plot(ctdtrim)
if (!interactive()) dev.off()
