if (!interactive()) png("482C.png")
library(oce)
system.time(l <- read.landsat("/data/archive/landsat/LC80150282014178LGN00", band="panchromatic"))
plot(l, col=oceColorsJet)
mtext(l[["time"]])
if (!interactive()) dev.off()
