library(oce)
#png("a.png", width=7, height=4, pointsize=9, unit='in', res=100)
par(mfcol=c(2,2))
imagep(adp[['time']], adp[['distance']], adp[['v']][,,1])
## turn off time range for rest of plots
options(oceDrawTimeRange=FALSE)
imagep(rev(adp[['time']]), rev(adp[['distance']]), adp[['v']][,,1])
oceContour(adp[['time']], adp[['distance']], adp[['v']][,,1])
oceContour(rev(adp[['time']]), rev(adp[['distance']]), adp[['v']][,,1], tformat="%H:%S")
#dev.off()
