library(oce)
try(source("~/src/oce/R/sw.R"))
try(source("~/src/oce/R/ctd.R"))
library(gsw)
data(ctd)
if (!interactive()) pdf("02_%d.pdf")
plotTS(ctd,eos='teos')
title("TEOS")
plotTS(ctd,eos='gsw')
title("GSW")
if (!interactive()) dev.off()
