library(oce)
##try(source("~/src/oce/R/section.R"))
data(section)
GS <- subset(section, 109<=stationId & stationId<=129)
if (!interactive()) png("763a.png")
plot(GS, span=500)
if (!interactive()) dev.off()
