## Show that plot() passes col (etc) to plotTS() and plotProfile()
library(oce)
load("testCTD.RData")
cm <- colormap(haul05.trim[["pressure"]])
if (!interactive()) png("issue1657.png")
par(mfrow=c(2, 1))
plot(haul05.trim, which=3, col=cm$zcol, pch=20, cex=2)
plotTS(haul05.trim, col=cm$zcol, pch=20, cex=2)
plotProfile(haul05.trim, xtype="fluorescence", type="p", col=cm$zcol, pch=20, cex=2)
plot(haul05.trim, which="fluorescence", type="p", col=cm$zcol, pch=20, cex=2)
if (!interactive()) dev.off()

