require(oce)
try({source('~/src/oce/R/map.R')})
data(coastlineWorld)
if (!interactive())
    png(filename="aitoff.png" ,hei=5, wid=8, uni='in', res=100)
par(mfrow=c(1,2), mar=c(2, 2, 1, 1))
mapPlot(coastlineWorld, proj="aitoff")
#mapPlot(coastlineWorld, proj="+proj=aitoff")
if (!interactive()) dev.off()

