library(oce)
source("~/src/oce/R/map.R")
# options(issue721=TRUE) # testing code Wed Aug 26, 2015 ("issue721" branch)
data(coastlineWorld)
data(topoWorld)
if (!interactive()) png("726a_%d.png", height=400)
par(mfrow=c(2,2), mar=c(3, 3, 1, 1))
mapPlot(coastlineWorld, proj='+proj=stere +lat_0=-90', longitudelim=c(-180, 180), latitudelim=c(-90, -70))
print(system.time(mapImage(topoWorld, colormap=colormap(name='gmt_relief'), filledContour=TRUE)))
mapLines(coastlineWorld[["longitude"]], coastlineWorld[["latitude"]], lwd=2)
mapPlot(coastlineWorld, proj='+proj=stere +lat_0=-90', longitudelim=c(-180, 180), latitudelim=c(-90, -70))
print(system.time(mapImage(topoWorld, colormap=colormap(name='gmt_relief'))))
mapLines(coastlineWorld[["longitude"]], coastlineWorld[["latitude"]], lwd=2)
## a spot near AA, in a region coloured green in left panel, light blue in right panel
p <- c(-175.82, -81.1)
ix <- which.min(abs(topoWorld[["longitude"]]-p[1]))
iy <- which.min(abs(topoWorld[["latitude"]]-p[2]))
latLook <- 0:10
mapPoints(topoWorld[["longitude"]][rep(ix, length(latLook))], topoWorld[["latitude"]][iy+latLook], pch='+')
par(mar=c(3, 3, 1, 1), mgp=c(2, 0.7, 0))
plot(topoWorld[["latitude"]][iy+latLook], topoWorld[["z"]][ix, iy+latLook],ylab="z", xlab="Lat", pch=20,
     ylim=c(-1000,0))
text(topoWorld[["latitude"]][iy+latLook], topoWorld[["z"]][ix, iy+latLook]-50, topoWorld[["z"]][ix, iy+latLook], pos=1, srt=90)
if (!interactive()) dev.off()
