library(oce)
try(source("~/src/oce/R/colors.R"))
if (!interactive()) png("636a.png")
par(mfrow=c(1,1))
data(topoWorld)
par(mfrow=c(2,1))
cm <- colormap(name="gmt_globe")
imagep(topoWorld, breaks=cm$breaks, col=cm$col)
cm <- colormap(name="gmt_globe", subdivisions=10)
str(cm)
imagep(topoWorld, breaks=cm$breaks, col=cm$col)
mtext("NOTE: broken near coastline (land bridge in Bering St)", font=2, col="purple")
if (!interactive()) dev.off()

