library(oce)
try(source("~/src/oce/R/sw.R"))
try(source("~/src/oce/R/ctd.R"))
library(gsw)
data(ctd)
if (!interactive()) png("02_teos.png", res=200, pointsize=11, width=7, height=7, unit="in")
plotTS(ctd,eos='teos')
title("TEOS")
if (!interactive()) dev.off()
if (!interactive()) png("02_gsw.png", res=200, pointsize=11, width=7, height=7, unit="in")
plotTS(ctd,eos='gsw')
title("GSW")
if (!interactive()) dev.off()
