library(oce)
try({source("~/src/oce/R/map.R")})
data(coastlineWorld)
if (!interactive()) png("541.png")
par(mfcol=c(2,2), mar=c(2, 2, 1.25, 1))
mapPlot(coastlineWorld)
mtext("EXPECT: grid but no axes", font=2, col="purple", adj=0)
mapPlot(coastlineWorld, axes=FALSE)
mtext("EXPECT: grid but no axes", font=2, col="purple", adj=0)
mapPlot(coastlineWorld, longitudelim=c(-70,70), latitudelim=c(-30,30), axes=TRUE)
mtext("EXPECT: grid with axes", font=2, col="purple", adj=0)
mapPlot(coastlineWorld, longitudelim=c(-70,70), latitudelim=c(-30,30), axes=FALSE)
mtext("EXPECT: grid but no axes", font=2, col="purple", adj=0)
if (!interactive()) dev.off()

