library(oce)
#try(source("~/src/oce/R/ctd.R"))
data(ctd)
set.seed(669)
n <- length(ctd[["salinity"]])
lon <- ctd[["longitude"]] + rnorm(n, sd=0.05)
lat <- ctd[["latitude"]] + rnorm(n, sd=0.05)
ctdnew <- as.ctd(ctd[['salinity']], ctd[['temperature']], ctd[['pressure']],
                 longitude = lon, latitude = lat)
if (!interactive()) png("669_1.png")
plot(ctd)
if (!interactive()) dev.off()
if (!interactive()) png("669_2.png")
plot(ctdnew)
if (!interactive()) dev.off()
