---
author: Dan Kelley
title: What is the frequency of the SA tidal constituent?
---

The table gives values of the frequency of the SA tidal constituent. Some
sources list speed, and others list frequency. To distinguish the two cases, a
$\dagger$ symbol indicates a source value.  Note that source values are reported
to the number of digits in the source Reference. By contrast, computed values
are always reported to 10 digits.

```{r echo=FALSE}
fc <- function(a,b) (a-b)/0.5/(a+b)
foce <- 0.0001140741
fnoaa <- 0.0001140794
fukmo1 <- 0.0001140750
fukmo2 <- 0.0001140794
A <- fc(foce, fnoaa)
B <- fc(fukmo1, fukmo2)
```

Notes:

1. Oce follows TIDPACK and T-TIDE, so the frequency values are not independent.
2. The wikipedia entry cites a NOAA sequence number, so the frequency values are not
   likely to be independent.
3. The fractional frequency difference between oce and NOAA is `r A`.
4. The fractional frequency difference between the old UKHO value and the newer one is `r B`.
5. The updated frequency in UKMO (2017) matches the much older entry in USDC (1940).

**Comment.** Comparison of notes 3 and 4 might suggest the hypothesis that the
oce vs NOAA difference results from an update in the best estimate of the SA
frequency since the 1970s, when TIDPACK was developed.  However, the most recent
UKHO (2017) value matches the USDC (1940) value, from 8 decades prior, which
argues against the idea of values evolving as new data become available.

| Speed (deg/hour)| Frequency (cycle/hour) | Source | Reference |
| ------- | --------- | ------- | ------------------------- |
|`r sprintf("%.10f", 0.0001140741*360)`|0.0001140741$\dagger$ | oce | http://www.github/com/dankelley/oce|
|`r sprintf("%.10f", 0.0001140741*360)`|0.0001140741$\dagger$ | TIDPACK | https://www.dfo-mpo.gc.ca/science/documents/data-donnees/tidal-marees/tidpack.zip|
|`r sprintf("%.10f", 0.0001140741*360)`|0.0001140741$\dagger$ | T-TIDE| https://www.eoas.ubc.ca/~rich/t_tide/t_tide_v1.2beta.zip |
|0.0410686$\dagger$|`r sprintf("%.10f", 0.0410686/360)`|NOAA (2023)|https://tidesandcurrents.noaa.gov/harcon.html?id=1612340|
|0.0410686$\dagger$|`r sprintf("%.10f", 0.0410686/360)` |Wikipedia (2023)| https://en.wikipedia.org/wiki/Theory_of_tides |
| 0.041067$\dagger$|`r sprintf("%.10f", 0.041067/360)`|UKHO (2017)|https://flaterco.com/files/xtide/Constituents-20170508.pdf|
| 0.0410686$\dagger$|`r sprintf("%.10f", 0.0410686/360)`|UKHO (2017)|second entry, an update to the above https://flaterco.com/files/xtide/Constituents-20170508.pdf|
|0.0410686|`r sprintf("%.10f", 0.0410686/360)`|USDC (1940) Table 2, page 180|https://tidesandcurrents.noaa.gov/publications/SpecialPubNo98.pdf|
