# 1954b.R: chunks start at cindex= 0 4677 6274 7871 9468 11065 12662 
all:
	#split -b 7870 tmp.ad2cp
	#?split -b 8473 tmp.ad2cp
	split -b 8470 tmp.ad2cp
	#split -b 12662 tmp.ad2cp
	od -x tmp.ad2cp | head -2
	od -x xaa | head -2
	od -x xab | head -2
	od -x xac | head -2

