library(oce)
rsk <- read.rsk('file.rsk')
str(rsk@metadata)
ctd <- as.ctd(rsk)
str(ctd@metadata)
if (!interactive()) png("642a.png")
plot(ctd)
title("EXPECT: 10<T<16 and 2<S<16 roughly", font=2, col.main='purple')
if (!interactive()) dev.off()
