library(oce)
data(sealevel)
m <- tidem(sealevel)
if (!interactive()) png("1021a.png")
par(mfrow=c(3,1))
plot(m)
plot(m, constituents=c("M2","S2","M4"),sides=c(3,1,3),col=1:3)
plot(m, constituents=c("M2","S2","M4"),sides=c(3,1,3),col=1:3, which=2)
if (!interactive()) dev.off()
