library(oce)
png("oce406-1.png")
drawPalette(zlim=c(0,1), col=oceColorsJet, pos=1, zlab="pos=1")
plot(co2)
dev.off()

png("oce406-2.png")
drawPalette(zlim=c(0,1), col=oceColorsJet, pos=2, zlab="pos=2")
plot(co2)
dev.off()

png("oce406-3.png")
drawPalette(zlim=c(0,1), col=oceColorsJet, pos=3, zlab="pos=3")
plot(co2)
dev.off()

png("oce406-4.png")
drawPalette(zlim=c(0,1), col=oceColorsJet, zlab="pos=4 (default)")
plot(co2)
dev.off()
