library(oce)
data("coastlineWorldFine", package="ocedata")
source("~/src/oce/R/adp.R")
source("~/src/oce/R/adp.rdi.R")
if (!interactive()) png("696a.png", width=7, height=4, unit="in", res=150, pointsize=9)
d <- read.adp("data.ENX")
par(mfrow=c(1,2), mar=c(3, 3, 1, 1), mgp=c(2, 0.7, 0))
plot(coastlineWorldFine, clon=d[["slongitude"]][1], clat=d[["slatitude"]][1], span=500)
points(d[["slongitude"]], d[["slatitude"]], col='red')
asp <- 1 / cos(pi/180*mean(d[["slatitude"]], na.rm=TRUE))
plot(d[["slongitude"]], d[["slatitude"]], type='p', asp=asp, pch=20, col='red',
     xlab="", ylab="")
points(d[["slongitude"]], d[["slatitude"]], col='blue')
segments(d[["slongitude"]], d[["slatitude"]], d[["elongitude"]], d[["elatitude"]], col='blue')
if (!interactive()) dev.off()
