library(oce)
data("coastlineWorldFine", package="ocedata")
source("~/src/oce/R/adp.R")
source("~/src/oce/R/adp.rdi.R")
if (!interactive()) png("696b.png", width=7, height=4, unit="in", res=150, pointsize=9)
d <- read.adp("data.ENX")
par(mfrow=c(5,1), mar=c(3, 3, 1, 1), mgp=c(2, 0.7, 0))
hist(d[["avgSpeed"]])
hist(d[["trackTrue"]])
hist(d[["trackMagnetic"]])
hist(d[["speedMadeGood"]])
hist(d[["directionMadeGood"]])

if (!interactive()) dev.off()
