library(oce)
try(source("~/src/oce/R/imagep.R"))
try(source("~/src/oce/R/adp.R"))
data(adp)
if (!interactive()) png("585A.png")
plot(adp, which=1, breaks=seq(-1, 1, 0.5), drawTimeRange=FALSE, debug=3)
mtext('EXPECT: 3 color levels between -1 and 1', col='magenta', font=2)
if (!interactive()) dev.off()
