rm(list=ls())
library(oce)
data(drifter)
drifterGrid <- drifterGrid(drifter)
ds <- subset(drifterGrid, pressure > 500 & pressure < 1000)
if (!interactive()) png('727a.png')
par(mfrow=c(1,2))
plot(drifter, which=5); legend('bottomleft', 'Original', text.col='purple', bg='white')
plot(ds, which=5, ylim=range(drifter[['pressure']])); legend('bottomleft', 'Subsetted by pressure', text.col='purple', bg='white')
if (!interactive()) dev.off()
