if (!interactive()) png("523.png", height=250)
library(oce)
try({ source("~/src/oce/R/map.R") })
data(coastlineWorld)
par(mfrow=c(2,1), mar=c(3, 3, 1, 1))
mapPlot(coastlineWorld, proj="+proj=moll")
mtext("EXPECT: no UHL (ugly spurious horiz lines)", font=2, col='purple', adj=0)
mtext("+proj=moll", adj=1)
cl <- coastlineCut(coastlineWorld, lon_0=180)
mapPlot(cl, proj="+proj=moll +lon_0=180")
mtext("EXPECT: no UHL", font=2, col='purple', adj=0)
mtext("+proj=moll +lon_0=180", adj=1)
if (!interactive()) dev.off()

