if (!interactive()) png("482D.png")
library(oce)
try({
    source('~/src/oce/R/landsat.R')
})
options(testLandsat1=TRUE)
system.time(l <- read.landsat("~/Downloads/LC80150282014178LGN00", band="panchromatic"))
plot(l, col=oceColorsJet)
mtext(l[["time"]])
if (!interactive()) dev.off()
