rm(list=ls())
## Similar to 449 but using precise data so can develop formal tests when bug fixed.
if (!interactive()) png("449b.png", width=7, height=4, unit="in", res=150, pointsize=9)

library(oce)
try(source('~/src/oce/R/colors.R'), silent=TRUE)
par(mfcol=c(2,2), mar=c(3, 3, 1, 1))
t <- seq(0, 1, length.out=100)
plim <- c(38, 41)
p <- mean(plim) + diff(plim) / 2 * cos(2 * pi * t)
zlim <- c(38.5, 40.5)
zline <- zlim                          # seq(38.5, 40.5, 0.5)
omar <- par('mar')

cm1 <- colormap(p, breaks=seq(zlim[1], zlim[2], 0.1), debug=3)
stopifnot(!any(is.na(cm1$zcol)))
drawPalette(colormap=cm1)
plot(t, p, type='p', pch=21, cex=1.5, bg=cm1$zcol) 
abline(h=zline)
mtext("1: colormap(p, breaks=...)", side=3, cex=3/4)
#mtext(sprintf("looks BAD to DK (range of palette should be %.2f to %.2f)", zlim[1], zlim[2]),
#      side=3, line=-1, font=2, cex=3/4)
mtext("looks OK  to DK", side=3, line=-1, font=2, cex=3/4)
mtext("looks OK to CR", side=3, line=-2, font=2, cex=3/4)

par(mar=omar)
cm2 <- colormap(p, zlim=zlim, debug=3)
stopifnot(!any(is.na(cm2$zcol)))
drawPalette(colormap=cm2, debug=0)
plot(t, p, type='p', pch=21, cex=1.5, bg=cm2$zcol) 
abline(h=zline)
mtext(paste("2: colormap(p, zlim=c(", zlim[1], ",", zlim[2], "))"), side=3, cex=3/4)
mtext("looks OKto DK", side=3, line=-1, font=2, cex=3/4)
mtext("looks OK to CR", side=3, line=-2, font=2, cex=3/4)

par(mar=omar)
cm3 <- colormap(p, breaks=seq(zlim[1], zlim[2], 0.1), zclip=TRUE, debug=3)
stopifnot(!any(is.na(cm3$zcol)))
drawPalette(colormap=cm3)
plot(t, p, type='p', pch=21, cex=1.5, bg=cm3$zcol) 
abline(h=zline)
mtext("3: colormap(z, breaks=..., zclip=TRUE)", side=3, cex=3/4)
mtext("looks OK  to DK", side=3, line=-1, font=2, cex=3/4)
mtext("looks OK to CR", side=3, line=-2, font=2, cex=3/4)

par(mar=omar)
cm4 <- colormap(p, zlim=zlim, breaks=11, zclip=TRUE, debug=3, missingColor='pink')
stopifnot(!any(is.na(cm4$zcol)))
drawPalette(colormap=cm4)
plot(t, p, type='p', pch=21, cex=1.5, bg=cm4$zcol) 
abline(h=zline)
mtext("4: colormap(p, zlim, zclip=TRUE)", side=3, cex=3/4)
mtext("looks OK  to DK", side=3, line=-1, font=2, cex=3/4)
mtext("looks OK to CR", side=3, line=-2, font=2, cex=3/4)

if (!interactive()) dev.off()

#message("range of p: ", min(p), " to ", max(p))
