if (!interactive()) png("475a1.png")
library(oce)
try({
    source('~/src/oce/R/ctd.R')
    source('~/src/oce/R/coastline.R')
    source('~/src/oce/R/map.R')
})
data(ctd)
##plot(ctd)
par(mfrow=c(2,1))
plot(ctd, which='map', span=3000)
#plot(ctd, which='map')
mapPoints(-60, 45)
mapScalebar("topleft", length=500)
if (!interactive()) dev.off()
message("grid lines should be on pretty(lat) etc")
message("mapScalebar broken")

