library(oce)
source("~/src/oce/R/map.R")
# options(issue721=TRUE) # testing code Wed Aug 26, 2015 ("issue721" branch)
data(coastlineWorld)
data(topoWorld)
if (!interactive()) png("721a_%d.png")
par(mfrow=c(1,2), mar=c(3, 3, 1, 1))
mapPlot(coastlineWorld, proj='+proj=stere +lat_0=-90', longitudelim=c(-180, 180), latitudelim=c(-90, -50))
print(system.time(mapImage(topoWorld, colormap=colormap(name='gmt_relief'), filledContour=TRUE)))
mapLines(coastlineWorld[["longitude"]], coastlineWorld[["latitude"]], lwd=2)
mapPlot(coastlineWorld, proj='+proj=stere +lat_0=-90', longitudelim=c(-180, 180), latitudelim=c(-90, -50))
print(system.time(mapImage(topoWorld, colormap=colormap(name='gmt_relief'))))
mapLines(coastlineWorld[["longitude"]], coastlineWorld[["latitude"]], lwd=2)
if (!interactive()) dev.off()

