if (!interactive()) png("490.png")
library(oce)
par(mfrow=c(2,2))
data(adp)
imagep(adp[['v']][,,1], zlim=c(0, 1))
mtext("EXPECT: no palette triangles")
imagep(adp[['v']][,,1], zlim=c(0, 1), drawTriangles=TRUE)
mtext("EXPECT: triangles")
imagep(adp[['v']][,,1], zlim=c(0, 1), drawTriangles=c(FALSE, TRUE))
mtext("EXPECT triangle @ top")
imagep(adp[['v']][,,1], zlim=c(0, 1), drawTriangles=c(TRUE, FALSE))
mtext("EXPECT triangle @ bottom")
if (!interactive()) dev.off()
