if (!interactive()) png("356B.R")
library(oce)
data(coastlineWorld)
data(topoWorld)
par(mar=c(1.5, 1.5, 2, 1))
lonlim <- c(-20, 20)
latlim <- c(50, 80)
drawPalette(zlim=c(-5000, 0), col=oceColorsJet)
mapPlot(coastlineWorld, longitudelim=lonlim, latitudelim=latlim, projection='stereographic')
mapImage(topoWorld, col=oceColorsJet, zlim=c(-5000, 0))
mapLines(coastlineWorld, col='grey')
#mapPolygon(coastlineWorld, col='grey')
mtext("EXPECT: colour reveal reasonable topo", font=2, col="purple", adj=0)
if (!interactive()) dev.off()
