if (!interactive()) png("402.png", width=7, height=7, unit="in", res=150, pointsize=12)

library(oce)
data(ctd)
plotProfile(ctd, xtype="salinity", type='p', pch=20, cex=1/2, ylim=c(10,0))
p <- seq(0, 45, 1)
d0 <- ctdDecimate(ctd, p=p)
d1 <- ctdDecimate(ctd, p=p, method=function(x,y,xout) runlm(x, y, xout, L=2)$y)
d2 <- ctdDecimate(ctd, p=p, method=function(x,y,xout) predict(smooth.spline(x, y, df=30), p)$y)
lines(d0[["salinity"]], d0[["pressure"]], col="black")
lines(d1[["salinity"]], d1[["pressure"]], col="red")
lines(d2[["salinity"]], d2[["pressure"]], col="blue")
if (!interactive()) dev.off()
