library(oce)
try(source("~/src/oce/R/ctd.R"))
data(ctd)
if (!interactive()) png("698.png")
par(mfrow=c(2,2))
plot(ctd, which="map")
mtext("(a) EXPECT as (c)", side=3, adj=0, font=2, col='magenta', line=-1.2, cex=0.7)
plot(ctd, which="map", coastline="coastlineWorldMedium")
mtext("(b) EXPECT: coarse", side=3, adj=0, font=2, col='magenta', line=-1.2, cex=0.7)
plot(ctd, which="map", coastline="coastlineWorldFine")
mtext("(c) EXPECT: as (a)", side=3, adj=0, font=2, col='magenta', line=-1.2, cex=0.7)
plot(ctd, which="map", span=50)
mtext("(d) EXPECT: (a) but zoomed out", side=3, adj=0, font=2, col='magenta', line=-1.2, cex=0.7)
if (!interactive()) dev.off()
