library(oce)
metfile <- download.met(43405, 2023, 12, "hour", type = "csv")
met1 <- read.met(metfile)
metfile <- download.met(43405, 2024, 1, "hour", type = "csv")
met2 <- read.met(metfile)
#source("~/git/oce/R/AllClass.R")
#source("~/git/oce/R/met.R")
met <- concatenate(met1, met2)#, debug = 1)
stopifnot(inherits(met1@data, "list"))
stopifnot(inherits(met2@data, "list"))
stopifnot(inherits(met@data, "list"))
if (!interactive()) png("2213a_%d.png", unit="in", width=7, height=5, pointsize=10, res=200)
plot(met1)
plot(met2)
plot(met)
if (!interactive()) dev.off()
