library(oce)
metfile <- download.met(43405, 2023, 12, "hour", type = "csv")
met1 <- read.met(metfile)
metfile <- download.met(43405, 2024, 1, "hour", type = "csv")
met2 <- read.met(metfile)
source("~/git/oce/R/AllClass.R")
source("~/git/oce/R/met.R")
met <- concatenate(met1, met2)#, debug = 1)
if (!interactive()) png("2213a.png", unit="in", width=7, height=5, pointsize=10, res=200)
plot(met)
if (!interactive()) dev.off()
