library(oce)
d <- read.oce("a.rsk")
stopifnot(abs(d[['pressure']][1]) < 1)
d <- read.rsk("a.rsk")
stopifnot(abs(d[['pressure']][1]) < 1)
d <- read.rsk("a.rsk", patm=TRUE)
stopifnot(abs(d[['pressure']][1]) < 1)
d <- read.rsk("a.rsk", patm=FALSE)
stopifnot(abs(10-d[['pressure']][1]) < 1)
d <- read.rsk("a.rsk", patm=10.1)
stopifnot(abs(d[['pressure']][1]) < 1)

