library(oce)
data(ctd)
if (!interactive()) png("671.png")
par(mfrow=c(2,2))
plotProfile(ctd)
mtext("(a)", line=0, adj=1, font=2)
plotProfile(ctd, ylim=c(30,20))
mtext("EXPECT: just 20-30db", col="magenta", line=0, adj=0, font=2)
mtext("(b)", line=0, adj=1, font=2)
plotProfile(ctd, plim=c(30,20))
mtext("EXPECT: as (b)", col="magenta", line=0, adj=0, font=2)
mtext("(c)", line=0, adj=1, font=2)
plotProfile(ctd, ytype="depth", plim=c(30,20))
mtext("EXPECT: as (a)", col="magenta", line=0, adj=0, font=2)
mtext("SINCE: ytype!='density'", col="magenta", line=-1, adj=0, font=2)
mtext("(d)", line=0, adj=1, font=2)
if (!interactive()) dev.off()
