library(oce)
try(source("~/src/oce/R/ctd.R"))
data(ctd)
scanRange <- range(ctd[['scan']])
prange <- range(ctd[['pressure']])
newScanRange <- c(scanRange[1] + 20, scanRange[2] - 20)
if (!interactive()) png("670b.png")
par(mfrow=c(2,1))
plotScan(ctd, xlim=scanRange, ylim=prange)
abline(v=newScanRange)
mtext('Original ctd object')
plotScan(ctdTrim(ctd, "scan", parameters=newScanRange),
         xlim=scanRange, ylim=prange)
mtext('Should be trimmed to vertical lines from above', col='purple', font=2)
if (!interactive()) dev.off()
