library(oce)
try(source("~/src/oce/R/logger.R"))
try(source("~/src/oce/R/sw.R"))
try(source("~/src/oce/R/ctd.R"))
logger <- read.logger("cast4.rsk")
ctd <- as.ctd(logger)
Slogger <- swSCTp(logger)
ctd <- as.ctd(logger)
Sctd <- swSCTp(ctd)
stopifnot(identical(Sctd, Slogger))

