library(oce)
try(source("~/src/oce/R/logger.R"))
try(source("~/src/oce/R/sw.R"))
try(source("~/src/oce/R/ctd.R"))
ctd <- read.logger("cast4.rsk")
S <- swSCTp(ctd)
rangeS <- range(S, na.rm=TRUE)
stopifnot(rangeS[1] > 0)
stopifnot(rangeS[2] < 40)
