library(oce)
try(source("~/src/oce/R/rsk.R"))
try(source("~/src/oce/R/sw.R"))
try(source("~/src/oce/R/ctd.R"))
rsk <- read.rsk("cast4.rsk")
ctd <- as.ctd(rsk)
Srsk <- swSCTp(rsk)
ctd <- as.ctd(rsk)
Sctd <- swSCTp(ctd)
stopifnot(identical(Sctd, Srsk))

