if (!interactive()) pdf("459.pdf")
library(oce)
data(section)
GS <- subset(section, -73.2 <= longitude & longitude <= -69.4)
GSdistance <- sectionSort(GS, by="longitude")
plot(GSdistance)
if (!interactive()) dev.off()
