library(oce)
data("coastlineWorldFine", package="ocedata")
## try(source("~/src/oce/R/adp.R"))
## try(source("~/src/oce/R/adp.rdi.R"))
if (!interactive()) png("696a.png", width=7, height=4, unit="in", res=150, pointsize=9)
d <- read.adp("data.ENX")
par(mfrow=c(1,2), mar=c(3, 3, 1, 1), mgp=c(2, 0.7, 0))
plot(coastlineWorldFine, clon=d[["firstLongitude"]][1], clat=d[["firstLatitude"]][1], span=500)
points(d[["firstLongitude"]], d[["firstLatitude"]], col='red')
asp <- 1 / cos(pi/180*mean(d[["firstLatitude"]], na.rm=TRUE))
plot(d[["firstLongitude"]], d[["firstLatitude"]], type='p', asp=asp, pch=20, col='red',
     xlab="", ylab="")
points(d[["firstLongitude"]], d[["firstLatitude"]], col='blue')
segments(d[["firstLongitude"]], d[["firstLatitude"]], d[["lastLongitude"]], d[["lastLatitude"]], col='blue')
if (!interactive()) dev.off()
